In [1]:
import numpy as np
import random

In [2]:
def select_elites(geno_type, fitness, num):
    """

    :param num: int
    :param fitness: numpy
    :param geno_type numpy
    :return: numpy
    """
    fitness = np.argsort(fitness)[::-1]
    elites = geno_type[fitness[:num]]
    return elites

In [3]:
geno_type = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
fitness = np.asarray([11,12,13])
elite_num = 1

In [4]:
print('geno_type')
print(geno_type)
print('fitness')
print(fitness)

geno_type
[[1 2 3]
 [4 5 6]
 [7 8 9]]
fitness
[11 12 13]


In [5]:
sum_fitness = 0
population = geno_type.shape[0]
situations = geno_type.shape[1]
print(population)
print(situations)
field = []
for pop_i in range(population):
    sum_fitness += fitness[pop_i]
    field.append(sum_fitness)
field = np.asarray(field, int)
print('field')
print(field)

3
3
field
[11 23 36]


In [13]:

new_geno_type = np.empty((0, situations), int)
elites = select_elites(geno_type, fitness, elite_num)

for geno_i in range(elite_num, population):
    print('geno_i', geno_i)
    roulette = random.randrange(0, sum_fitness)
    print(roulette)
    select_index = np.where(field >= roulette)[0]
    print(select_index)
    print(select_index[0])
    select_index = select_index[0]
    new_geno_type = np.append(new_geno_type, geno_type[select_index])
print(new_geno_type)

geno_i 1
7
[0 1 2]
0
geno_i 2
26
[2]
2
[1 2 3 7 8 9]


In [16]:
a = np.asarray([[1,2],[3,4]])
b = np.asarray([[4,5],[6,7]])
print(np.r_[a,b])

[[1 2]
 [3 4]
 [4 5]
 [6 7]]
