In [1]:
import numpy as np
import random
import pprint




In [2]:
    def select_elites(geno_type, fitness, num):
        """

        :param num: int
        :param fitness: numpy
        :param geno_type numpy
        :return: numpy
        """
        fitness = np.argsort(fitness)[::-1]
        elites = geno_type[fitness[:num]]
        return elites

In [3]:
geno_type = np.asarray([[1,2,3], [4,5,6], [7,8,9]])
fitness = np.asarray([10, 11, 12])
elite_num = 1
mutation = 70
cross = 2
situation = [(1, 50), (2, 100), (1, 50)]


sum_fitness = 0
population = geno_type.shape[0]
situations = geno_type.shape[1]
print('before')
print(geno_type)
field = []
for pop_i in range(population):
    sum_fitness += fitness[pop_i]
    field.append(fitness[pop_i])
field = np.asarray(field, int)
new_geno_type = np.empty((0, situations), int)
elites = select_elites(geno_type, fitness, elite_num)




before
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
for geno_i in range(elite_num, population):
    roulette = random.randrange(0, sum_fitness)
    select_index = np.where(field >= roulette)[0]
    new_geno_type = np.append(new_geno_type, geno_type[select_index])
print('for. 1')
print(geno_type)


for. 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
for geno_i in range(elite_num, population, 2):
    rand = random.randrange(0, 100)
    if rand >= cross:
        continue
    pair_i = geno_i + 1
    cut_point = random.randrange(0, situations - 1)
    geno_type[geno_i] = np.asarray(np.r_[new_geno_type[geno_i][:cut_point],
                                         new_geno_type[pair_i][cut_point + 1:]], int)
    geno_type[pair_i] = np.asarray(np.r_[new_geno_type[pair_i][:cut_point],
                                         new_geno_type[geno_i][cut_point + 1:]], int)
print('for. 2')
print(geno_type)


for. 2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
for geno_i in range(elite_num, population):
    for situ_i in range(situations):
        rand = random.randrange(0, 100)
        if rand >= mutation:
            continue
        value = situation[situ_i]
        geno_type[geno_i][situ_i] = random.randrange(value[0], value[1])
print('for 3.')
print(geno_type)
rest = geno_type[elite_num:]
print('rest')
print(rest)
print('elites')
print(elites)
geno_type = np.asarray(np.r_[elites, rest], int)
print('after')
print(geno_type)

for 3.
[[ 1  2  3]
 [26 46 41]
 [ 7 33 20]]
rest
[[26 46 41]
 [ 7 33 20]]
elites
[[7 8 9]]
after
[[ 7  8  9]
 [26 46 41]
 [ 7 33 20]]


In [47]:
def select_elites(geno_type, fitness, num):
        """

        :param num: int
        :param fitness: numpy
        :param geno_type numpy
        :return: numpy
        """
        fitness = np.argsort(fitness)[::-1]
        print(fitness)
        print(fitness[:num])
        print(geno_type)
        elites = geno_type[fitness[:num - 1]]
        return elites

In [48]:
elites = select_elites(geno_type, fitness, 1)
print(elites)

[2 1 0]
[2]
[[ 4 16 30]
 [45 99  9]]
[]


In [46]:
arr = np.asarray([1, 2, 3, 4])
print(arr[1])
print(arr[[1,2]])

2
[2 3]
